mkdir ~/strands
cd ~/strands
f() {
curl "$1/" | grep '<span id.* hidden>' > "`basename "$1"`"
}
f https://customstrandsnyt.com/play/August-10-2024O-J-z-k-D
f https://customstrandsnyt.com/play/August-09-2024R-n-j-u-N
f https://customstrandsnyt.com/play/August-08-2024Q-Q-g-Y-A
f https://customstrandsnyt.com/play/August-07-2024K-m-g-Y-m
f https://customstrandsnyt.com/play/August-06-2024K-Y-K-c-Q
f https://customstrandsnyt.com/play/August-05-2024w-S-X-N-I
f https://customstrandsnyt.com/play/August-04-2024M-b-Z-O-B
f https://customstrandsnyt.com/play/August-03-2024l-V-N-T-m
f https://customstrandsnyt.com/play/August-02-2024M-W-f-W-o
f https://customstrandsnyt.com/play/August-01-2024N-A-P-F-O
f https://customstrandsnyt.com/play/July-31-2024o-a-O-T-v
f https://customstrandsnyt.com/play/July-30-2024w-w-b-t-t
f https://customstrandsnyt.com/play/July-29-2024v-c-l-w-C
f https://customstrandsnyt.com/play/July-28-2024R-U-b-R-H
f https://customstrandsnyt.com/play/July-27-2024F-e-Q-D-j
f https://customstrandsnyt.com/play/July-26-2024k-d-b-D-y
f https://customstrandsnyt.com/play/July-25-2024R-w-Z-r-v
f https://customstrandsnyt.com/play/July-24-2024w-N-i-Y-M
f https://customstrandsnyt.com/play/July-23-2024Y-r-A-q-O
f https://customstrandsnyt.com/play/July-22-2024E-r-R-s-O
f https://customstrandsnyt.com/play/July-21-2024C-A-y-U-x
f https://customstrandsnyt.com/play/July-20-2024s-k-a-k-M
f https://customstrandsnyt.com/play/July-19-2024D-I-d-D-c
f https://customstrandsnyt.com/play/July-18-2024I-k-f-u-F
f https://customstrandsnyt.com/play/July-17-2024o-g-w-i-g
f https://customstrandsnyt.com/play/July-16-2024c-w-P-b-E
f https://customstrandsnyt.com/play/July-15-2024B-D-P-v-h
f https://customstrandsnyt.com/play/July-14-2024N-p-H-x-x
f https://customstrandsnyt.com/play/July-13-2024O-T-K-t-s
f https://customstrandsnyt.com/play/July-12-2024i-J-s-C-S
f https://customstrandsnyt.com/play/July-11-2024v-O-y-P-C
f https://customstrandsnyt.com/play/July-10-2024x-T-Z-r-f
f https://customstrandsnyt.com/play/July-09-2024q-N-A-D-P
f https://customstrandsnyt.com/play/July-08-2024C-S-W-L-E
f https://customstrandsnyt.com/play/July-07-2024d-A-W-r-j
f https://customstrandsnyt.com/play/July-06-2024Y-w-g-f-U
f https://customstrandsnyt.com/play/July-05-2024B-c-e-q-I
f https://customstrandsnyt.com/play/July-04-2024J-r-b-w-S
f https://customstrandsnyt.com/play/July-03-2024Q-Y-Y-L-K
f https://customstrandsnyt.com/play/July-02-2024l-t-z-D-C
f https://customstrandsnyt.com/play/July-01-2024W-a-V-h-Y
f https://customstrandsnyt.com/play/June-30-2024g-Z-w-H-P
f https://customstrandsnyt.com/play/June-29-2024E-J-a-v-q
f https://customstrandsnyt.com/play/June-28-2024W-h-Y-d-n
f https://customstrandsnyt.com/play/June-27-2024q-E-l-l-h
f https://customstrandsnyt.com/play/June-26-2024V-N-b-K-e
f https://customstrandsnyt.com/play/June-25-2024z-P-i-I-z
f https://customstrandsnyt.com/play/June-24-2024Z-z-o-L-h
f https://customstrandsnyt.com/play/June-23-2024J-E-P-F-M
f https://customstrandsnyt.com/play/June-22-2024D-I-I-K-L
f https://customstrandsnyt.com/play/June-21-2024Y-Q-J-D-m
f https://customstrandsnyt.com/play/June-20-2024h-p-e-I-j
f https://customstrandsnyt.com/play/June-19-2024d-X-G-S-p
f https://customstrandsnyt.com/play/June-18-2024v-e-b-p-m
f https://customstrandsnyt.com/play/June-17-2024Z-x-z-O-C
f https://customstrandsnyt.com/play/June-16-2024b-e-A-K-S
f https://customstrandsnyt.com/play/June-15-2024o-w-K-D-A
f https://customstrandsnyt.com/play/June-14-2024r-g-N-J-N
f https://customstrandsnyt.com/play/June-13-2024w-n-T-E-Q
f https://customstrandsnyt.com/play/June-12-2024d-R-Y-k-f
f https://customstrandsnyt.com/play/June-11-2024U-C-H-C-X
f https://customstrandsnyt.com/play/June-10-2024T-N-F-L-w
f https://customstrandsnyt.com/play/June-09-2024D-M-t-w-c
f https://customstrandsnyt.com/play/June-08-2024w-D-j-T-t
f https://customstrandsnyt.com/play/June-07-2024r-e-v-R-N
f https://customstrandsnyt.com/play/June-06-2024g-Z-J-C-s
f https://customstrandsnyt.com/play/June-05-2024G-n-s-f-g
f https://customstrandsnyt.com/play/June-4-2024s-w-V-Z-C
f https://customstrandsnyt.com/play/June-3-2024S-Z-t-q-i
f https://customstrandsnyt.com/play/June-2-2024K-x-K-k-l
f https://customstrandsnyt.com/play/June-1-2024B-J-L-e-v
f https://customstrandsnyt.com/play/May-31-2024f-v-O-y-z
f https://customstrandsnyt.com/play/May-30-2024W-m-P-I-I
f https://customstrandsnyt.com/play/May-29-2024G-P-Q-l-u
f https://customstrandsnyt.com/play/May-28-2024i-i-T-j-N
f https://customstrandsnyt.com/play/May-27-2024a-B-c-P-n
f https://customstrandsnyt.com/play/May-26-2024m-j-u-Y-l
f https://customstrandsnyt.com/play/May-25-2024S-n-l-m-H
f https://customstrandsnyt.com/play/May-24-2024E-W-x-G-q
f https://customstrandsnyt.com/play/May-23-2024y-E-i-r-I
f https://customstrandsnyt.com/play/May-22-2024q-z-i-q-v
f https://customstrandsnyt.com/play/May-21-2024b-U-i-s-L
f https://customstrandsnyt.com/play/May-20-2024M-g-r-F-O
f https://customstrandsnyt.com/play/May-19-2024p-I-j-m-x
f https://customstrandsnyt.com/play/May-18-2024X-I-a-V-G
f https://customstrandsnyt.com/play/May-17-2024F-N-d-U-f
f https://customstrandsnyt.com/play/May-16-2024M-c-N-Z-n
f https://customstrandsnyt.com/play/May-15-2024d-X-i-i-B
f https://customstrandsnyt.com/play/May-14-2024d-H-g-H-F
f https://customstrandsnyt.com/play/May-13-2024R-b-t-C-t
f https://customstrandsnyt.com/play/May-12-2024k-E-M-K-z
f https://customstrandsnyt.com/play/May-11-2024m-k-y-L-E
f https://customstrandsnyt.com/play/May-10-2024I-q-B-d-j
f https://customstrandsnyt.com/play/May-9-2024q-H-m-l-L
f https://customstrandsnyt.com/play/May-8-2024I-k-f-J-H
f https://customstrandsnyt.com/play/May-7-2024j-y-z-D-J
f https://customstrandsnyt.com/play/May-6-2024T-y-c-P-n
f https://customstrandsnyt.com/play/May-5-2024n-B-L-a-c
f https://customstrandsnyt.com/play/May-4-2024C-W-u-U-D
f https://customstrandsnyt.com/play/May-3-2024U-F-r-z-Q
f https://customstrandsnyt.com/play/May-2-2024n-M-U-j-E
f https://customstrandsnyt.com/play/May-1-2024S-E-H-q-u
f https://customstrandsnyt.com/play/April-30-2024h-M-l-g-z
f https://customstrandsnyt.com/play/April-29-2024r-x-e-n-a
f https://customstrandsnyt.com/play/April-28-2024J-G-K-W-h
f https://customstrandsnyt.com/play/April-27-2024b-C-i-H-g
f https://customstrandsnyt.com/play/April-26-2024B-H-I-X-x
f https://customstrandsnyt.com/play/April-25-2024P-X-g-U-q
f https://customstrandsnyt.com/play/April-24-2024j-J-h-p-T
f https://customstrandsnyt.com/play/April-23-2024P-i-d-g-D
f https://customstrandsnyt.com/play/April-22-2024I-K-w-k-b
f https://customstrandsnyt.com/play/April-21-2024s-d-l-f-Z
f https://customstrandsnyt.com/play/April-20-2024s-p-c-K-P
f https://customstrandsnyt.com/play/April-19-2024n-B-B-o-H
f https://customstrandsnyt.com/play/April-18-2024x-O-b-K-N
f https://customstrandsnyt.com/play/April-17-2024W-z-h-a-g
f https://customstrandsnyt.com/play/April-16-2024C-G-C-P-D
f https://customstrandsnyt.com/play/April-15-2024i-Z-f-Y-P
f https://customstrandsnyt.com/play/April-14-2024M-G-y-M-O
f https://customstrandsnyt.com/play/April-13-2024h-q-p-c-s
f https://customstrandsnyt.com/play/April-12-2024F-V-o-Z-L
f https://customstrandsnyt.com/play/April-11-2024G-g-R-B-q
f https://customstrandsnyt.com/play/April-10-2024T-l-y-Z-x
f https://customstrandsnyt.com/play/April-9-2024C-m-h-y-x
f https://customstrandsnyt.com/play/April-8-2024W-C-g-Q-Y
f https://customstrandsnyt.com/play/April-7-2024P-g-m-r-n
f https://customstrandsnyt.com/play/April-6-2024l-D-T-Y-L
f https://customstrandsnyt.com/play/April-5-2024K-I-Q-U-E
f https://customstrandsnyt.com/play/April-4-2024d-z-i-a-I
f https://customstrandsnyt.com/play/April-3-2024l-m-f-a-F
f https://customstrandsnyt.com/play/April-2-2024D-V-j-i-m
f https://customstrandsnyt.com/play/April-1-2024k-i-A-G-Q
f https://customstrandsnyt.com/play/March-31-2024Q-Y-u-v-h
f https://customstrandsnyt.com/play/March-30-2024A-B-O-e-y
f https://customstrandsnyt.com/play/March-29-2024z-l-G-L-I
f https://customstrandsnyt.com/play/March-28-2024P-C-f-j-N
f https://customstrandsnyt.com/play/March-27-2024P-O-F-K-h
f https://customstrandsnyt.com/play/March-26-2024F-b-b-Q-d
f https://customstrandsnyt.com/play/March-25-2024C-r-m-g-U
f https://customstrandsnyt.com/play/March-24-2024t-v-L-D-O
f https://customstrandsnyt.com/play/March-23-2024m-O-m-D-i
f https://customstrandsnyt.com/play/March-22-2024T-C-K-B-V
f https://customstrandsnyt.com/play/March-21-2024H-c-h-O-n
f https://customstrandsnyt.com/play/March-20-2024i-U-P-a-o
f https://customstrandsnyt.com/play/March-19-2024o-j-i-O-O
f https://customstrandsnyt.com/play/March-18-2024W-V-f-o-F
f https://customstrandsnyt.com/play/March-17-2024u-i-a-l-Q
f https://customstrandsnyt.com/play/March-16-2024A-A-A-A-A
f https://customstrandsnyt.com/play/March-15-2024s-I-A-X-O
f https://customstrandsnyt.com/play/March-14-2024o-M-N-x-r
f https://customstrandsnyt.com/play/March-13-2024m-M-I-m-m
f https://customstrandsnyt.com/play/March-12-2024E-E-z-Q-O
f https://customstrandsnyt.com/play/March-11-2024l-R-v-s-d
f https://customstrandsnyt.com/play/March-10-2024V-z-s-s-m
f https://customstrandsnyt.com/play/March-9-2024Z-s-x-R-t
f https://customstrandsnyt.com/play/March-8-2024M-v-f-k-W
f https://customstrandsnyt.com/play/March-7-2024W-l-I-v-h
f https://customstrandsnyt.com/play/March-6-2024X-D-K-a-j
f https://customstrandsnyt.com/play/March-5-2024x-A-E-l-O
f https://customstrandsnyt.com/play/March-4-2024l-j-l-F-Q
